name: Publish Docs
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
jobs:
  publish:
    name: Publish Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
          
      - name: Cache .nuke/temp, ~/.nuget/packages
        uses: actions/cache@v2
        with:
          path: |
            Tools/.nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
          
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: Tools/Docusaurus/package-lock.json
          
      - name: Build Docs
        working-directory: Tools/Nuke
        run: ./build.cmd DocusaurusBuild
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Tools/Docusaurus/build
          cname: udonsharp.docs.vrchat.com
